# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#
plugins: [jekyll-paginate]


title: Alba's blog
email: dqh725@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  LeBlanc’s law: Later equals never.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.cheeger.com" # the base hostname & protocol for your site
github_username:  dqh725

# Build settings
markdown: kramdown

# enable pagination for posts
paginate: 5
